FROM ocamlpro/ocaml:5.1.0 AS base

FROM base AS builder

WORKDIR /app

COPY . .

RUN opam switch create . ocaml-system --deps --locked && \
  opam exec -- dune build

EXPOSE 8080

ENV PORT 8080
ENV HOSTNAME "0.0.0.0"

CMD ["./_build/default/bin/main.exe"]
