import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { client } from "../lib/client";
import {
  EnumPostsQuery,
  EnumPostsDocument,
} from "../graphql/queries/enumPosts.generated";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import type { Post } from "../types";

type Props = {
  posts: Post[];
};

export async function getStaticProps() {
  const result = await client.query<EnumPostsQuery>({
    query: EnumPostsDocument,
  });

  if (result.loading || !result?.data?.blogPostCollection?.items) {
    return {
      props: { posts: [] as Post[] },
    };
  }
  const posts: (Post | null | undefined)[] =
    result.data.blogPostCollection.items;

  return {
    props: { posts },
  };
}

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>腐ったコロッケ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>腐ったコロッケ</h1>

        <div className={styles.grid}>
          {posts.map((post) => (
            <Link key={post.sys.id} href={`/posts/${post.slug}`} passHref>
              <div className={styles.card}>
                <h2>{post.title}</h2>
                <p>{post.description}</p>
              </div>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
